# Generated by Django 3.2.25 on 2025-03-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
    ]
