# Generated by Django 3.2.25 on 2025-03-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='expires_on',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='subscribed_on',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro')], default='Free', max_length=50),
        ),
    ]
