# Generated by Django 3.2.25 on 2025-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('block_reason', models.TextField()),
                ('is_permanent', models.BooleanField(default=False)),
                ('unblock_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
