# Generated by Django 3.2.25 on 2025-03-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_automationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.website'),
        ),
    ]
